version: '3.8'

services:
  web:
    build: .
    command: python car_shop/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src.app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "5433:5432"

volumes:
  postgres_data: