# Generated by Django 4.1.1 on 2022-09-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Sed', 'Sedan'), ('Cab', 'Cabriolet'), ('Van', 'Minivan'), ('Cou', 'Coupe'), ('Pic', 'Pickup'), ('Hat', 'Hatchback')], default='Sed', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Client'), (2, 'Provider'), (3, 'Shop Manager'), (4, 'Admin')], default=0),
        ),
    ]
