# Generated by Django 4.1.1 on 2022-09-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerhistory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='providerhistory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='providerhistory',
            name='updated',
        ),
    ]
