# Generated by Django 4.1.1 on 2022-09-11 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shophistory_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcar',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
